### ISSUE TITLE
Extend cc-xmp-tag to allow for a User Agent

### ISSUE THREAD

**Issue by mattl** [creativecommons/seneca#3]
Right now, it just references the perl library, it would be nice if we could extend this in some way to add support to show that it came from The List, etc

**Comment by mattl** [comment]
http://regex.info/exif.cgi?imgurl=https%3A%2F%2Fthelist.creativecommons.org%2Fapp%2Flive%2Fprocess-me-9-dk8sER.jpg

**Comment by asmith15** [comment]
Fixed in d1c02ce: you can set CreatorTool to whatever you want.
